### ISSUE TITLE
Non-transferable AID is the same as its public key.

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/tswg-did-method-webs-specification#15]
In the AID Value Section in [did-method-webs/spec/diddocs.md](https://github.com/dhh1128/did-method-webs/blob/main/spec/diddocs.md#aid-value), it says " If the AID is non-transferable (does not support key rotation) the AID is generated by taking a cryptographic digest of the first (and only) public key of the identifier." 

If I understand correctly, a non-transferable AID is the same as its public key, not its digest.

**Comment by dhh1128** [comment]
I think the text is correct when it says that the AID is a hash of the public key rather than the direct value of the public key. This text was written by @pfeairheller, who can confirm or update.

We may remove mentions to non-transferrable mode anyway; see #6 .

**Comment by 2byrds** [comment]
The KERI spec says it's a choice... I take that to mean you could us either the public key OR the digest of non-transferrable inception.... for the did:webs spec I believe this is close enough. Will reopen the issue if needed:
"A special case may arise when the set of public keys has only one member, i.e. there is only one controlling keypair. In this case, the controller of the identifier may choose to use only the qualified public key as the identifier instead of a qualified digest of the incepting information. In this case, the identifier is still strongly bound to the public key but is not so strongly bound to any other incepting information. A variant of this single keypair special case is an identifier that can not be rotated. Another way of describing an identifier that cannot be rotated is that it is a non-transferable identifier because control over the identifier cannot be transferred to a different set of controlling keypairs."
