### ISSUE TITLE
add a sentence about which HTTP methods we assume (only GET)

### ISSUE THREAD

**Issue by dhh1128** [trustoverip/tswg-did-method-webs-specification#20]

**Comment by peacekeeper** [comment]
I'm not quite sure what this issue is about.

In the ["Read (Resolve)"](https://trustoverip.github.io/tswg-did-method-webs-specification/#read-resolve) section we currently say this:

> The reader then does a GET on both the URL for the DID document (ending in /did.json) and on the URL for the KERI event stream (ending in /did.keri)

In the ["Create (Register)"](https://trustoverip.github.io/tswg-did-method-webs-specification/#create-register) section we say this:

> Create the AID folder on the web server at the selected location, and place the DID document and the KERI event stream file into that folder.

I think how EXACTLY those resources are placed on the web server is intentionally left out of scope, i.e. we probably don't want to define some kind of REST API using e.g. the PUT method here.

Or does this issue apply more to the Signed Files section, rather than DID document and KERI event stream?

**Comment by dhh1128** [comment]
What I am looking for is a sentence that says something like this: "The only HTTP method that must be implemented on did:webs URLs by a web server is GET." As you said, I want to explicitly put other stuff out of scope.

I am happy to write such a sentence, but I didn't want to create something unless/until I got a signal that others felt like I did.
