### ISSUE TITLE
DID doc publisher should be under the authority of the AID controller(s)

### ISSUE THREAD

**Issue by 2byrds** [trustoverip/tswg-did-method-webs-specification#28]
From our 2023 August 31 meeting, Sam/Phil discussed:
The did doc publisher should be under the authority of the controller(s) of the KEL/AID (or perhaps a delegated AID of the contorller). We would not want an unauthorized non-controller (random or nefarious) to be regarded as a legitimate publisher of a did:webs did document.

**Comment by dhh1128** [comment]
I don't think we have this risk, if the KEL/TEL has to record the URL at which the KEL is published. Am I wrong?

**Comment by 2byrds** [comment]
> I don't think we have this risk, if the KEL/TEL has to record the URL at which the KEL is published. Am I wrong?

Yes, I agree that anchoring the did:webs to the KEL/TEL is a simple/thorough strategy. It looks like we have agreement in the group on that. So we'll add information about the events that support this.

IF in the future there will be other options as well, like a DID document published for discovery purposes and thus using the BADA RUN security characteristics.... then we need to document that for the reader so that they can understand the difference between the two, especially from a security PoV.

**Comment by peacekeeper** [comment]
Is this really a problem, if I publish somebody else's KERI event stream on my domain name?

What attacks or other problems can this possibly enable?

In pretty much any DID method, I can add somebody else's public keys into my DID document, so what, what's the harm? I can't prove control of the DID anyway, since I don't have the private keys.

**Comment by swcurran** [comment]
IMHO — there is no problem with publishing a DID and all of it’s data on another web server. The “id” and any “alsoKnownAs” entries in the DIDDoc would not match the location of the DID, but there is not a problem.

The use of “id” and the ability to (in Web terms) redirect the discovery of the DIDDoc (etc.) to use another web location is so that after the redirection, DIDs that may exist in published documents anywhere in the world (e.g. in registries, verifiable credentials, and so on) that point to the old site can be seen verified on the new as being intentional synonyms defined by the controller.

Of course, that works fine if the web redirection is automatic. It doesn’t do so well if there is not a web redirection and the resolver has to use some other discovery technique. The AID and the KERI log enables verification wherever they are found.

**Comment by 2byrds** [comment]
Designated aliases feature as documented, handles the authority of the domain hosting the did:webs identifier
