### ISSUE TITLE
Caching question in processing a KERI event log

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#43]
This question came up several weeks ago in a call, and was also recently raised in a recent Slack channel question. I thought it worth raising as an issue here, for possible inclusion in a "resolver implementer's Guide".

@SmithSamuelM talked about the efficiency of keeping around key state and processing just the added events when necessary, vs. always processing the event log from scratch to prove verifiability.

My understanding/expectation about this is that a resolver will retrieve and process the KERI log set of events, which in turn will produce interim and a final DIDDoc. As well, the DIDDoc corresponding to the KERI log will also be published on the web server and can be retrieved directly — and verified against the derived one (from the events).

Given that the KERI event format is append only, I think that it should be possible for a resolver to:

* Cache the KERI state derived from the event log, the current event log file length, a hash of the file, and the related DIDDoc.
* Retrieve a new KERI state.
* If the hash is the same, all done (no change to the file)
* Use the cached file length to jump in the file to where previous processing stopped, and
* Continue processing the events, and updating the cached state.

Is that technically possible?

Is that implemented such that a resolver could use that tactic of using cached data in the processing of commonly resolved, frequently updated KERI identifiers?

**Comment by SmithSamuelM** [comment]
That is how any verifier that verifies a KEL can work. The code in keripy that does this type of verification is used in multiple places. More specifically its verifying a CESR Stream and a CESR stream can include streamed KELs. The CESR stream parser code then hands off as appropriate any KEY events in the stream to a Key Event Verifier (called a KEVer) In KERI parlance this stream parsing and Key Event Verification code is a library run by  some component like a watcher, witness, controller, etc that is in essense "watching" a KEL. In the did:webs case the key event verifier is the did resolver.  

The complication I want to avoid is in moving the verification to be downstream of the did doc rendering. I.e. interposing the did doc in the append only key event verification process. I don't see a reason to do that and it doesn't appear that that is what your are asking. I just wanted to clarify that that is not the case. 

That means that in general we let the  did resolver be a Key event verifier (technically CESR Stream parser that hands off to a key event verifier) and how it chooses to do that verification is implementation dependent.  Certainly, becasue of the append only architecture (which by design enables incremental verification at scale) one can leverage that in doing a from scratch implementation of a KEL verifier in the form of a did resolver in order to render a did doc. But if you are using Python you can just import the keripy packages that do the parsing and key event verification for you and you don't have to write any new code other than to glue it on.

**Comment by SmithSamuelM** [comment]
In keripy we use LMDB which is a highly performant persistent b-tree key value store that enables asynchronous append-only key event verification at scale. But if performance is not so important you could use a file as your append only incremental cache.

**Comment by SmithSamuelM** [comment]
One of concerns with KERI light did methods like did:plc is that they haven't yet thought through the corner cases and are making some insecure naive assumptions.

**Comment by 2byrds** [comment]
@swcurran and @SmithSamuelM this was an excellent issue to discuss and that I hope ties a bow on the discussions over the last month regarding .kel, .oobi, .keri, .cesr files/resources/streams. The current spec jargon that several PRs have migrated to, is the encompassing term 'KERI event stream'. KERI event stream is the CESR stream that @SmithSamuelM is referring to. And it is generic (agnostic) to how the KELs/TELs are being stored/updated/retrieved. When the resolver receives the GET command for the did:webs .keri **resource** the resolver could do all kinds of interesting things with files, databases, watcher code, etc. to get the KERI event stream for that AID and verify the DID Document. The spec will remain agnostic to those infrastructure/impl details, only specifying that a GET on the .keri resource is necessary to get the needed KERI event stream. 

@swcurran you are describing a way that a resolver could handle generation and verification using files containing the KERI event stream needed. That implementation doesn't exist but the spec is agnostic to those implementation details, except to specify the security characteristics that have to accounted for (if any are missing, we must add them).
@SmithSamuelM gave a general description with some important info, then described an already implemented way of verifying a did:webs DID document using the existing KERI python code that watchers, etc use. The details like using LMDB won't be discussed in the spec, but that implementation already exists and is very efficient so that is what the resolver reference implementation that @peacekeeper and I are building on.

From the spec perspective we just say that the resolver needs the 'KERI event stream' found at the .keri web resource and then the spec will soon describe the KERI events (inception, rotation, interaction, etc) that a 'KERI event stream' will provide in order to provide the verification of the DID document.

Happy to discuss further so that we are all in agreement about the division between what the spec says vs. what a refernce implementation might support. To discuss implementation details we should discuss in the [reference implementation repository here](https://github.com/hyperledger-labs/did-webs-resolver) -or if a different reference impl is started, it could be discussed there.

**Comment by swcurran** [comment]
The only thing I was after in this was if what I asked about was technically possible (seems like yes) and if it was already implemented such that a did:webs resolver could use it today (seem like that is a no).  So possible, and worth mentioning in an implementers guide if the concerns @SmithSamuelM raised at the meeting a couple of weeks back becomes an issue.

Happy to close this as resolved.
